import type { Dictionary } from "@/i18n/types";

export const vi = {
  meta: { siteName: "Private Social Insights", description: "Phân tích quan hệ Instagram ưu tiên quyền riêng tư, tách biệt với tiện ích Tin công khai." },
  a11y: { skipToContent: "Chuyển đến nội dung chính", primaryNavigation: "Điều hướng chính", legalNavigation: "Điều hướng pháp lý", language: "Ngôn ngữ", theme: "Giao diện", closeDialog: "Đóng hộp thoại" },
  nav: { analyzer: "Phân tích", stories: "Tin", howItWorks: "Cách hoạt động", faq: "Hỏi đáp", privacy: "Quyền riêng tư", terms: "Điều khoản", homeLabel: "Trang chủ Private Social Insights" },
  locale: { english: "English", vietnamese: "Tiếng Việt" },
  theme: { system: "Theo hệ thống", light: "Sáng", dark: "Tối" },
  footer: { localBoundary: "Bản xuất dữ liệu quan hệ của bạn chỉ ở trên thiết bị này.", storyBoundary: "Tra cứu Tin công khai là một tính năng mạng riêng biệt." },
  home: { eyebrow: "Riêng tư từ kiến trúc", title: "Hiểu thay đổi quan hệ mà không giao mật khẩu của bạn.", description: "Phân tích bản xuất Instagram JSON chính thức ngay trong trình duyệt. Tra cứu Tin công khai là tính năng mạng riêng biệt và được thông báo rõ.", openAnalyzer: "Mở công cụ phân tích", howItWorks: "Cách hoạt động", principlesLabel: "Nguyên tắc sản phẩm", noLoginTitle: "Không đăng nhập tài khoản", noLoginBody: "Chúng tôi không yêu cầu mật khẩu, cookie, access token hay mã xác thực hai bước Instagram.", localTitle: "Phân tích quan hệ cục bộ", localBody: "ZIP quan hệ và dữ liệu người theo dõi đã chuẩn hóa được xử lý trên thiết bị này.", boundariesTitle: "Ranh giới minh bạch", boundariesBody: "Yêu cầu Tin qua mạng được tách khỏi lịch sử quan hệ cục bộ của bạn.", storyCtaTitle: "Bạn đang tìm Tin hoặc Tin nổi bật công khai?", storyCtaBody: "Tiện ích đó dùng yêu cầu server/nhà cung cấp được công bố và không đọc cơ sở dữ liệu quan hệ cục bộ.", storyCtaAction: "Xem tiện ích Tin" },
  pages: {
    analyzer: { eyebrow: "Phân tích quan hệ cục bộ", title: "Bản xuất dữ liệu ở lại trên thiết bị của bạn.", description: "Bộ máy nhập cục bộ an toàn đã sẵn sàng; quy trình phân tích có hướng dẫn sẽ được kết nối ở cột mốc UX tiếp theo.", notice: "ZIP và JSON được phân tích cục bộ trong worker riêng. Không file nào được tải lên và không cần thông tin đăng nhập Instagram." },
    stories: { eyebrow: "Tiện ích mạng riêng biệt", title: "Xem Tin công khai với ranh giới quyền riêng tư rõ ràng.", description: "Khi được bật, handle công khai đã nhập sẽ được gửi tới server và nhà cung cấp đã cấu hình, và có thể xuất hiện trong log vận hành theo chính sách của nhà cung cấp. Bản xuất quan hệ không bao giờ nằm trong yêu cầu này.", notice: "Tra cứu Tin chưa được bật. Tính năng chỉ hỗ trợ tài khoản công khai, tôn trọng kiểm soát truy cập và bản quyền, và không yêu cầu thông tin đăng nhập Instagram." },
    howItWorks: { eyebrow: "Đơn giản và minh bạch", title: "Nhập bản xuất chính thức, nhận phân tích riêng tư.", description: "Tải bản xuất JSON từ Meta, kiểm tra cục bộ, xác nhận thời điểm snapshot, rồi so sánh với snapshot trước đó đã lưu trong trình duyệt này." },
    faq: { eyebrow: "Hỏi đáp", title: "Sản phẩm làm được gì — và không làm được gì.", description: "Công cụ so sánh bản xuất quan hệ chính thức ngay trên thiết bị. Một handle biến mất không chứng minh hành động bỏ theo dõi có chủ ý: đổi username, vô hiệu hóa, xóa, đình chỉ tài khoản hoặc khác biệt giữa các bản xuất đều có thể là nguyên nhân." },
    privacy: { eyebrow: "Quyền riêng tư", title: "Hai tính năng, hai ranh giới dữ liệu rõ ràng.", description: "Bản xuất quan hệ được giữ cục bộ. Khi bật tra cứu Tin, chỉ handle công khai đã nhập được gửi qua server tới nhà cung cấp và có thể nằm trong log vận hành của họ." },
    terms: { eyebrow: "Điều khoản", title: "Sử dụng dịch vụ có trách nhiệm.", description: "Chỉ phân tích dữ liệu bạn được phép sử dụng và chỉ tải media công khai khi bạn sở hữu hoặc được phép lưu. Dịch vụ này không liên kết hay được Meta hoặc Instagram chứng thực." },
  },
  analyzer: {
    account: { title: "Tài khoản cục bộ", label: "Nhãn tài khoản", username: "Username Instagram (không bắt buộc)", create: "Tạo tài khoản", select: "Chọn tài khoản", edit: "Sửa tài khoản" },
    import: { title: "Nhập bản xuất", zip: "Chọn ZIP", json: "Chọn các file JSON", cancel: "Hủy nhập", privacy: "File được xử lý cục bộ và không tải lên.", stages: { validating: "Đang kiểm tra", scanning_archive: "Đang quét kho lưu trữ", reading_relationship_files: "Đang đọc file quan hệ", parsing_json: "Đang phân tích JSON", normalizing: "Đang chuẩn hóa quan hệ", fingerprinting: "Đang tạo dấu vân tay", complete: "Hoàn tất" } },
    review: { title: "Kiểm tra bản nhập", snapshotDate: "Thời điểm snapshot", save: "Lưu snapshot", cancel: "Hủy", duplicate: "Dữ liệu này đã tồn tại cho tài khoản.", notSaved: "Kết quả phân tích vẫn còn, nhưng lịch sử chưa được lưu." },
    results: { followers: "Người theo dõi", following: "Đang theo dõi", mutuals: "Theo dõi lẫn nhau", notFollowingBack: "Không theo dõi lại bạn", notFollowedByMe: "Bạn chưa theo dõi lại", lostFollowers: "Người theo dõi đã mất", newFollowers: "Người theo dõi mới", netChange: "Thay đổi ròng người theo dõi" },
    history: { title: "Lịch sử snapshot", compare: "So sánh snapshot", previous: "Snapshot trước", empty: "Nhập snapshot khác sau này để xem thay đổi theo thời gian." },
    delete: { snapshotTitle: "Xóa snapshot?", snapshotBody: "Thao tác này xóa snapshot cục bộ đã chọn.", accountTitle: "Xóa tài khoản cục bộ?", accountBody: "Mọi snapshot đã lưu cho tài khoản này cũng sẽ bị xóa.", allTitle: "Xóa toàn bộ dữ liệu cục bộ?", allBody: "Thao tác này xóa mọi tài khoản, snapshot và cài đặt ứng dụng khỏi trình duyệt.", confirm: "Xóa", cancel: "Giữ dữ liệu" },
    diagnostics: { title: "Báo cáo tương thích", copy: "Sao chép báo cáo", copied: "Đã sao chép báo cáo" },
    csv: { export: "Xuất CSV", filename: "phan-tich-quan-he", category: "Nhóm", handle: "Handle", connectedAt: "Ngày kết nối" },
  },
  story: { label: "Handle Instagram công khai", submit: "Xem Tin công khai", disclosure: "Handle công khai đã nhập được gửi tới server và nhà cung cấp. Log vận hành của nhà cung cấp có thể lưu handle theo chính sách của họ.", copyright: "Chỉ tải media bạn sở hữu hoặc được phép lưu.", loading: "Đang tìm nội dung công khai…", empty: "Không tìm thấy Tin công khai đang hoạt động.", private: "Tài khoản này riêng tư hoặc không khả dụng. Công cụ không vượt qua kiểm soát truy cập.", rateLimited: "Có quá nhiều yêu cầu. Vui lòng đợi trước khi thử lại.", providerUnavailable: "Nhà cung cấp Tin tạm thời không khả dụng.", download: "Tải media" },
  errors: {
    import: { UNSUPPORTED_FILE_TYPE: "Chọn file ZIP hoặc JSON được hỗ trợ.", ARCHIVE_TOO_LARGE: "Kho lưu trữ vượt giới hạn kích thước cục bộ.", ARCHIVE_CORRUPTED: "Không thể đọc ZIP một cách an toàn.", ARCHIVE_ENCRYPTED: "Không hỗ trợ ZIP có mật khẩu.", ARCHIVE_TOO_MANY_ENTRIES: "Kho lưu trữ có quá nhiều file.", ARCHIVE_UNSAFE_PATH: "Kho lưu trữ chứa đường dẫn không an toàn.", ARCHIVE_SUSPICIOUS_COMPRESSION: "Kho lưu trữ có tỷ lệ nén đáng ngờ.", RELEVANT_DATA_TOO_LARGE: "Dữ liệu quan hệ vượt giới hạn an toàn.", FOLLOWERS_FILE_NOT_FOUND: "Không tìm thấy file người theo dõi được hỗ trợ.", FOLLOWING_FILE_NOT_FOUND: "Không tìm thấy file đang theo dõi được hỗ trợ.", INCOMPLETE_MULTIPART_FOLLOWERS: "Bộ file người theo dõi nhiều phần chưa đầy đủ.", UNSUPPORTED_HTML_EXPORT: "Hãy chọn định dạng xuất JSON thay vì HTML.", INVALID_JSON: "Một file quan hệ đã chọn không phải JSON hợp lệ.", UNSUPPORTED_INSTAGRAM_SCHEMA: "Định dạng bản xuất Instagram này chưa được hỗ trợ.", NO_VALID_RELATIONSHIPS: "Không tìm thấy quan hệ hợp lệ.", RELATIONSHIP_LIMIT_EXCEEDED: "Số lượng quan hệ vượt giới hạn an toàn.", IMPORT_CANCELLED: "Đã hủy nhập dữ liệu.", INDEXEDDB_UNAVAILABLE: "Lưu trữ lịch sử cục bộ không khả dụng.", INDEXEDDB_QUOTA_EXCEEDED: "Trình duyệt không còn dung lượng lưu trữ cục bộ.", SNAPSHOT_DUPLICATE: "Snapshot này đã tồn tại.", UNKNOWN_IMPORT_ERROR: "Không thể hoàn tất nhập dữ liệu." },
    persistence: { INDEXEDDB_UNAVAILABLE: "Lưu trữ lịch sử cục bộ không khả dụng.", INDEXEDDB_QUOTA_EXCEEDED: "Trình duyệt không còn dung lượng lưu trữ cục bộ.", PERSISTENCE_TRANSACTION_FAILED: "Giao dịch lưu cục bộ thất bại.", PERSISTENCE_MIGRATION_FAILED: "Không thể nâng cấp cơ sở dữ liệu cục bộ.", UNKNOWN_PERSISTENCE_ERROR: "Không thể lưu lịch sử cục bộ.", ACCOUNT_NOT_FOUND: "Tài khoản cục bộ đã chọn không còn tồn tại.", SNAPSHOT_NOT_FOUND: "Snapshot đã chọn không còn tồn tại.", SNAPSHOT_DUPLICATE: "Snapshot này đã tồn tại cho tài khoản.", SNAPSHOT_TIMESTAMP_CONFLICT: "Một snapshot khác dùng cùng ngày giờ.", INVALID_ACCOUNT_LABEL: "Nhập nhãn tài khoản cục bộ hợp lệ.", INVALID_ACCOUNT_USERNAME: "Nhập username Instagram hợp lệ.", INVALID_SNAPSHOT: "Metadata snapshot không hợp lệ.", INVALID_SETTING: "Giá trị cài đặt không hợp lệ.", DELETION_CONFIRMATION_REQUIRED: "Xác nhận xóa trước khi tiếp tục." },
  },
  warnings: { MULTIPART_FOLLOWERS_MERGED: "Đã gộp nhiều file người theo dõi.", DUPLICATE_HANDLES_REMOVED: "Đã loại bỏ handle trùng.", INVALID_ENTRY_SKIPPED: "Đã bỏ qua các quan hệ không hợp lệ.", MISSING_OPTIONAL_TIMESTAMP: "Một số ngày quan hệ không khả dụng.", UNKNOWN_NON_CRITICAL_FILE_IGNORED: "Đã bỏ qua file không liên quan.", LARGE_EXPORT_PERFORMANCE_WARNING: "Bản xuất lớn này có thể cần nhiều thời gian hơn.", MANUAL_IMPORT_COMPLETENESS_UNVERIFIED: "Hãy xác nhận bạn đã chọn mọi phần followers.", TIMESTAMP_CONFLICT_RESOLVED: "Các ngày quan hệ xung đột đã được xử lý thận trọng.", HISTORICAL_COUNT_INCONSISTENCY: "Số liệu lịch sử không nhất quán với chênh lệch đã tính." },
  common: { retry: "Thử lại", returnHome: "Về trang chủ", errorEyebrow: "Đã xảy ra lỗi", errorTitle: "Không thể hiển thị trang này.", errorBody: "Dữ liệu quan hệ cục bộ của bạn chưa được gửi đi đâu.", notFoundEyebrow: "404", notFoundTitle: "Không tìm thấy trang", notFoundBody: "Địa chỉ có thể không đúng hoặc trang đã được chuyển." },
} as const satisfies Dictionary;
